// <auto-generated />
namespace InoDrive.Domain.MigrationsAuthContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AnotherOne : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AnotherOne));
        
        string IMigrationMetadata.Id
        {
            get { return "201506062322481_AnotherOne"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
